# Generated by Django 2.0.1 on 2018-03-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=255, verbose_name='description')),
                ('options', models.CharField(max_length=255, verbose_name='options')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('courseID', models.ForeignKey(on_delete='courseID', related_name='Chioce_courseID', to='dispatch.Course')),
            ],
        ),
    ]
