# Generated by Django 2.0.3 on 2018-05-25 09:55

from django.db import migrations, models
import django.db.models.deletion
import exam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0002_auto_20180525_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1, verbose_name='userID')),
                ('courseID', models.CharField(max_length=10)),
                ('e_type', models.CharField(max_length=10)),
                ('file', models.FileField(blank=True, upload_to=exam.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.TextField(help_text='参考形式：我国交通事故报警求救电话号码是__[空1]__，以此类推', verbose_name='题干')),
                ('blank1', models.CharField(blank=True, max_length=255, verbose_name='空1')),
                ('blank2', models.CharField(blank=True, max_length=255, verbose_name='空2')),
                ('blank3', models.CharField(blank=True, max_length=255, verbose_name='空3')),
                ('blank4', models.CharField(blank=True, max_length=255, verbose_name='空4')),
                ('blank5', models.CharField(blank=True, max_length=255, verbose_name='空5')),
                ('blank6', models.CharField(blank=True, max_length=255, verbose_name='空6')),
                ('sec', models.CharField(default=0, max_length=10, verbose_name='考点')),
                ('point', models.IntegerField(default=0, verbose_name='分值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('courseID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Blank_courseID', to='dispatch.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.TextField(verbose_name='题干')),
                ('is_single', models.BooleanField(default=True, help_text='若为多选题，请勿勾选', verbose_name='是否单选')),
                ('A', models.CharField(blank=True, max_length=255, verbose_name='选项A')),
                ('B', models.CharField(blank=True, max_length=255, verbose_name='选项B')),
                ('C', models.CharField(blank=True, max_length=255, verbose_name='选项C')),
                ('D', models.CharField(blank=True, max_length=255, verbose_name='选项D')),
                ('E', models.CharField(blank=True, max_length=255, verbose_name='选项E')),
                ('F', models.CharField(blank=True, max_length=255, verbose_name='选项F')),
                ('answer', models.CharField(blank=True, help_text='参考形式：单选：A，多选：ABCD', max_length=4, verbose_name='答案')),
                ('sec', models.CharField(default=0, max_length=10, verbose_name='考点')),
                ('point', models.IntegerField(default=0, verbose_name='分值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('courseID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Chioce_courseID', to='dispatch.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='试卷题目')),
                ('intro', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('draft_string', models.TextField(verbose_name='草稿')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('courseID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Draft_courseID', to='dispatch.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='试卷题目')),
                ('intro', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('blanks', models.ManyToManyField(blank=True, related_name='Exam_blanks', to='exam.Blank')),
                ('choices', models.ManyToManyField(blank=True, related_name='Exam_choices', to='exam.Choice')),
                ('courseID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exam_courseID', to='dispatch.Course')),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.TextField(verbose_name='题干')),
                ('answer', models.BooleanField(help_text='勾选表示正确，不勾选表示错误', verbose_name='答案')),
                ('sec', models.CharField(default=0, max_length=10, verbose_name='考点')),
                ('point', models.IntegerField(default=0, verbose_name='分值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('courseID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Judge_courseID', to='dispatch.Course')),
            ],
        ),
        migrations.CreateModel(
            name='S_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.TextField(verbose_name='题干')),
                ('answer', models.TextField(blank=True, verbose_name='答案')),
                ('sec', models.CharField(default=0, max_length=10, verbose_name='考点')),
                ('point', models.IntegerField(default=0, verbose_name='分值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('courseID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='S_answer_courseID', to='dispatch.Course')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='Exam_judges', to='exam.Judge'),
        ),
        migrations.AddField(
            model_name='exam',
            name='s_answers',
            field=models.ManyToManyField(blank=True, related_name='Exam_s_answers', to='exam.S_answer'),
        ),
        migrations.AddField(
            model_name='draft',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Draft_examID', to='exam.Exam'),
        ),
    ]
