# Generated by Django 2.0.3 on 2018-04-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='sec',
            field=models.CharField(blank=True, max_length=255, verbose_name='考点'),
        ),
    ]
