# Generated by Django 2.0.1 on 2018-03-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '__first__'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('is_practice', models.BooleanField(default=True, verbose_name='is_practice')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('intro', models.CharField(max_length=255, verbose_name='intro')),
                ('courseID', models.ForeignKey(on_delete='courseID', related_name='Exam_courseID', to='dispatch.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='options',
        ),
        migrations.AddField(
            model_name='choice',
            name='A',
            field=models.CharField(blank=True, max_length=255, verbose_name='A'),
        ),
        migrations.AddField(
            model_name='choice',
            name='B',
            field=models.CharField(blank=True, max_length=255, verbose_name='B'),
        ),
        migrations.AddField(
            model_name='choice',
            name='C',
            field=models.CharField(blank=True, max_length=255, verbose_name='C'),
        ),
        migrations.AddField(
            model_name='choice',
            name='D',
            field=models.CharField(blank=True, max_length=255, verbose_name='D'),
        ),
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.CharField(blank=True, max_length=4, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='choice',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='grade'),
        ),
    ]
