# Generated by Django 2.0.1 on 2018-04-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_choice_sec'),
    ]

    operations = [
        migrations.AddField(
            model_name='blank',
            name='sec',
            field=models.CharField(blank=True, max_length=255, verbose_name='考点'),
        ),
        migrations.AddField(
            model_name='judge',
            name='sec',
            field=models.CharField(blank=True, max_length=255, verbose_name='考点'),
        ),
        migrations.AddField(
            model_name='s_answer',
            name='sec',
            field=models.CharField(blank=True, max_length=255, verbose_name='考点'),
        ),
    ]
