# Generated by Django 2.0.1 on 2018-03-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20180305_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='grade',
        ),
        migrations.AddField(
            model_name='choice',
            name='E',
            field=models.CharField(blank=True, max_length=255, verbose_name='E'),
        ),
        migrations.AddField(
            model_name='choice',
            name='F',
            field=models.CharField(blank=True, max_length=255, verbose_name='F'),
        ),
    ]
