# Generated by Django 2.0.1 on 2018-03-07 11:58

from django.db import migrations, models
import exam.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20180307_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.CharField(max_length=10)),
                ('e_type', models.CharField(max_length=10)),
                ('file', models.FileField(blank=True, upload_to=exam.models.user_directory_path)),
            ],
        ),
    ]
