# Generated by Django 2.0.1 on 2018-03-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_bankprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankprocess',
            name='user_id',
            field=models.IntegerField(default=1, verbose_name='userID'),
        ),
    ]
