# Generated by Django 2.0.1 on 2018-04-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20180426_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blank',
            name='sec',
            field=models.CharField(default=0, max_length=10, verbose_name='考点'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='sec',
            field=models.CharField(default=0, max_length=10, verbose_name='考点'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='sec',
            field=models.CharField(default=0, max_length=10, verbose_name='考点'),
        ),
        migrations.AlterField(
            model_name='s_answer',
            name='sec',
            field=models.CharField(default=0, max_length=10, verbose_name='考点'),
        ),
    ]
