# Generated by Django 2.0.1 on 2018-03-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_bankprocess_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_single',
            field=models.BooleanField(default=True, verbose_name='is_single'),
        ),
    ]
