# Generated by Django 2.0.1 on 2018-03-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '__first__'),
        ('exam', '0006_choice_is_single'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=255, verbose_name='description')),
                ('blank1', models.CharField(blank=True, max_length=255, verbose_name='blank1')),
                ('blank2', models.CharField(blank=True, max_length=255, verbose_name='blank2')),
                ('blank3', models.CharField(blank=True, max_length=255, verbose_name='blank3')),
                ('blank4', models.CharField(blank=True, max_length=255, verbose_name='blank4')),
                ('blank5', models.CharField(blank=True, max_length=255, verbose_name='blank5')),
                ('blank6', models.CharField(blank=True, max_length=255, verbose_name='blank6')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('courseID', models.ForeignKey(on_delete='courseID', related_name='Blank_courseID', to='dispatch.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=255, verbose_name='description')),
                ('answer', models.BooleanField(verbose_name='answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('courseID', models.ForeignKey(on_delete='courseID', related_name='Judge_courseID', to='dispatch.Course')),
            ],
        ),
        migrations.CreateModel(
            name='S_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descri', models.CharField(max_length=255, verbose_name='description')),
                ('answer', models.CharField(blank=True, max_length=255, verbose_name='answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('courseID', models.ForeignKey(on_delete='courseID', related_name='S_answer_courseID', to='dispatch.Course')),
            ],
        ),
    ]
