# Generated by Django 2.0.1 on 2018-03-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_blank_judge_s_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_answer',
            name='answer',
            field=models.TextField(blank=True, verbose_name='answer'),
        ),
    ]
