# Generated by Django 2.0.1 on 2018-03-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20180308_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blank',
            name='blank1',
            field=models.CharField(blank=True, max_length=255, verbose_name='空1'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='blank2',
            field=models.CharField(blank=True, max_length=255, verbose_name='空2'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='blank3',
            field=models.CharField(blank=True, max_length=255, verbose_name='空3'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='blank4',
            field=models.CharField(blank=True, max_length=255, verbose_name='空4'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='blank5',
            field=models.CharField(blank=True, max_length=255, verbose_name='空5'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='blank6',
            field=models.CharField(blank=True, max_length=255, verbose_name='空6'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='descri',
            field=models.TextField(verbose_name='题干'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='A',
            field=models.CharField(blank=True, max_length=255, verbose_name='选项A'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='B',
            field=models.CharField(blank=True, max_length=255, verbose_name='选项B'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='C',
            field=models.CharField(blank=True, max_length=255, verbose_name='选项C'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='D',
            field=models.CharField(blank=True, max_length=255, verbose_name='选项D'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='E',
            field=models.CharField(blank=True, max_length=255, verbose_name='选项E'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='F',
            field=models.CharField(blank=True, max_length=255, verbose_name='选项F'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.CharField(blank=True, max_length=4, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='descri',
            field=models.TextField(verbose_name='题干'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_single',
            field=models.BooleanField(default=True, verbose_name='是否单选'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='answer',
            field=models.BooleanField(verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='descri',
            field=models.TextField(verbose_name='题干'),
        ),
        migrations.AlterField(
            model_name='s_answer',
            name='answer',
            field=models.TextField(blank=True, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='s_answer',
            name='descri',
            field=models.TextField(verbose_name='题干'),
        ),
    ]
