# Generated by Django 2.0.1 on 2018-03-09 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20180308_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='is_practice',
        ),
        migrations.AddField(
            model_name='exam',
            name='blanks',
            field=models.ManyToManyField(related_name='Exam_blanks', to='exam.Blank'),
        ),
        migrations.AddField(
            model_name='exam',
            name='choices',
            field=models.ManyToManyField(related_name='Exam_choices', to='exam.Choice'),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='judges',
            field=models.ManyToManyField(related_name='Exam_judges', to='exam.Judge'),
        ),
        migrations.AddField(
            model_name='exam',
            name='s_answers',
            field=models.ManyToManyField(related_name='Exam_s_answers', to='exam.S_answer'),
        ),
        migrations.AlterField(
            model_name='blank',
            name='descri',
            field=models.TextField(help_text='参考形式：我国交通事故报警求救电话号码是__[空1]__，以此类推', verbose_name='题干'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='answer',
            field=models.CharField(blank=True, help_text='参考形式：单选：A，多选：ABCD', max_length=4, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_single',
            field=models.BooleanField(default=True, help_text='若为多选题，请勿勾选', verbose_name='是否单选'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='answer',
            field=models.BooleanField(help_text='勾选表示正确，不勾选表示错误', verbose_name='答案'),
        ),
    ]
