# Generated by Django 2.0.1 on 2018-03-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20180309_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='blanks',
            field=models.ManyToManyField(blank=True, related_name='Exam_blanks', to='exam.Blank'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='Exam_choices', to='exam.Choice'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='Exam_judges', to='exam.Judge'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='s_answers',
            field=models.ManyToManyField(blank=True, related_name='Exam_s_answers', to='exam.S_answer'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
