# Generated by Django 2.0.1 on 2018-03-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20180309_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='blank',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='分值'),
        ),
        migrations.AddField(
            model_name='choice',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='分值'),
        ),
        migrations.AddField(
            model_name='judge',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='分值'),
        ),
        migrations.AddField(
            model_name='s_answer',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='分值'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='courseID',
            field=models.ForeignKey(on_delete='课程', related_name='Exam_courseID', to='dispatch.Course'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='intro',
            field=models.CharField(blank=True, max_length=255, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=64, verbose_name='试卷题目'),
        ),
    ]
