# Generated by Django 2.0.1 on 2018-03-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20180310_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blank',
            old_name='grade',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='grade',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='judge',
            old_name='grade',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='s_answer',
            old_name='grade',
            new_name='point',
        ),
    ]
