# Generated by Django 2.0.1 on 2018-03-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '__first__'),
        ('exam', '0013_auto_20180311_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_json', models.CharField(max_length=255, verbose_name='草稿')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_time')),
                ('courseID', models.ForeignKey(on_delete='课程', related_name='Draft_courseID', to='dispatch.Course')),
            ],
        ),
    ]
