# Generated by Django 2.0.1 on 2018-03-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='draft_json',
            field=models.TextField(verbose_name='草稿'),
        ),
    ]
