# Generated by Django 2.0.1 on 2018-03-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20180313_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='draft_json',
            new_name='draft_string',
        ),
    ]
