# Generated by Django 2.0.1 on 2018-03-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20180313_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='intro',
            field=models.CharField(blank=True, max_length=255, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='draft',
            name='title',
            field=models.CharField(blank=True, max_length=64, verbose_name='试卷题目'),
        ),
    ]
