# Generated by Django 2.0.1 on 2018-03-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_auto_20180316_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='from_random',
            new_name='status',
        ),
    ]
