# Generated by Django 2.0.3 on 2018-04-04 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='电子邮箱')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='管理员')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='激活')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('user_id', models.CharField(error_messages={'unique': '该学号已存在.'}, help_text='Required. 10 characters. Digital only', max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='学号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='教师')),
                ('name', models.CharField(max_length=25, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='Female', max_length=255)),
                ('dept', models.CharField(max_length=255, verbose_name='学院')),
                ('major', models.CharField(max_length=255, verbose_name='专业')),
                ('phonenumber', models.CharField(max_length=11, null=True, verbose_name='联系号码')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('user_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
    ]
