# Generated by Django 2.0.3 on 2018-05-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='grade',
            field=models.IntegerField(choices=[(0, '待评分'), (1, '驳回'), (55, 'C'), (65, 'B'), (75, 'A'), (85, 'A+'), (95, 'A++')], default=0),
        ),
    ]
