# Generated by Django 2.0.1 on 2018-01-31 11:34

import UploadMulti.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileSimpleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='userID')),
                ('file_name', models.CharField(max_length=255, verbose_name='filename')),
                ('file', models.FileField(upload_to=UploadMulti.models.user_directory_path, verbose_name='filepath')),
                ('tiemstamp', models.CharField(max_length=255, verbose_name='uploadtime')),
                ('note', models.TextField(max_length=255, verbose_name='note')),
            ],
        ),
    ]
